export const CREATE_SESSION_API_TYPE = 'CREATE_SESSION_API_TYPE';
export const CLEAR_CREATE_SESSION_API_TYPE = 'CLEAR_CREATE_SESSION_API_TYPE';

export const CREATE_ACCESS_TOKEN_API_TYPE = 'CREATE_ACCESS_TOKEN_API_TYPE';
export const CLEAR_CREATE_ACCESS_TOKEN_API_TYPE = 'CLEAR_CREATE_ACCESS_TOKEN_API_TYPE';

export const GET_PACKS_API_TYPE = 'GET_PACKS_API_TYPE';
export const CLEAR_GET_PACKS_API_TYPE = 'CLEAR_GET_PACKS_API_TYPE';

export const SAVE_PACKS_API_TYPE = 'SAVE_PACKS_API_TYPE';
export const CLEAR_SAVE_PACKS_API_TYPE = 'CLEAR_SAVE_PACKS_API_TYPE';

export const PAGE_REDIRECTION_API_TYPE = 'PAGE_REDIRECTION_API_TYPE';
export const CLEAR_PAGE_REDIRECTION_API_TYPE = 'CLEAR_PAGE_REDIRECTION_API_TYPE';

export const PAGE_SUMMARY_API_TYPE = 'PAGE_SUMMARY_API_TYPE';
export const CLEAR_PAGE_SUMMARY_API_TYPE = 'CLEAR_PAGE_SUMMARY_API_TYPE';